USE [master]
GO

/****** Object:  Database [FreeCourseWebApi]    Script Date: 12/28/2021 10:30:43 PM ******/
CREATE DATABASE [FreeCourseWebApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FreeCourseWebApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FreeCourseWebApi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FreeCourseWebApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FreeCourseWebApi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FreeCourseWebApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FreeCourseWebApi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET ARITHABORT OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FreeCourseWebApi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FreeCourseWebApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FreeCourseWebApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FreeCourseWebApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FreeCourseWebApi] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FreeCourseWebApi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FreeCourseWebApi] SET  MULTI_USER 
GO

ALTER DATABASE [FreeCourseWebApi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FreeCourseWebApi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FreeCourseWebApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FreeCourseWebApi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FreeCourseWebApi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FreeCourseWebApi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FreeCourseWebApi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FreeCourseWebApi] SET  READ_WRITE 
GO

